package com.cheng.domain;

public class CartItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.cartItemId
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    private String cartitemid;

    @Override
	public String toString() {
		return "CartItem [cartitemid=" + cartitemid + ", quantity=" + quantity
				+ ", bid=" + bid + ", uid=" + uid + ", shunxu=" + shunxu + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.quantity
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.bid
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.uid
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.shunxu
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    private Integer shunxu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.cartItemId
     *
     * @return the value of cartitem.cartItemId
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    public String getCartitemid() {
        return cartitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.cartItemId
     *
     * @param cartitemid the value for cartitem.cartItemId
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    public void setCartitemid(String cartitemid) {
        this.cartitemid = cartitemid == null ? null : cartitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.quantity
     *
     * @return the value of cartitem.quantity
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.quantity
     *
     * @param quantity the value for cartitem.quantity
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.bid
     *
     * @return the value of cartitem.bid
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.bid
     *
     * @param bid the value for cartitem.bid
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.uid
     *
     * @return the value of cartitem.uid
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.uid
     *
     * @param uid the value for cartitem.uid
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.shunxu
     *
     * @return the value of cartitem.shunxu
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    public Integer getShunxu() {
        return shunxu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.shunxu
     *
     * @param shunxu the value for cartitem.shunxu
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    public void setShunxu(Integer shunxu) {
        this.shunxu = shunxu;
    }
}