package com.cheng.domain;

import java.math.BigDecimal;

public class myOrder {
    @Override
	public String toString() {
		return "myOrder [oid=" + oid + ", ordertime=" + ordertime + ", total="
				+ total + ", status=" + status + ", address=" + address
				+ ", uid=" + uid + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.oid
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.ordertime
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    private String ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.total
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.status
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.address
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.uid
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.oid
     *
     * @return the value of myorder.oid
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.oid
     *
     * @param oid the value for myorder.oid
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.ordertime
     *
     * @return the value of myorder.ordertime
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public String getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.ordertime
     *
     * @param ordertime the value for myorder.ordertime
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public void setOrdertime(String ordertime) {
        this.ordertime = ordertime == null ? null : ordertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.total
     *
     * @return the value of myorder.total
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.total
     *
     * @param total the value for myorder.total
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.status
     *
     * @return the value of myorder.status
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.status
     *
     * @param status the value for myorder.status
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.address
     *
     * @return the value of myorder.address
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.address
     *
     * @param address the value for myorder.address
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.uid
     *
     * @return the value of myorder.uid
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.uid
     *
     * @param uid the value for myorder.uid
     *
     * @mbggenerated Tue Jun 27 10:48:43 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }
}