package com.cheng.domain;

import java.math.BigDecimal;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oid
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordertime
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    private String ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.address
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.uid
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oid
     *
     * @return the value of order.oid
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oid
     *
     * @param oid the value for order.oid
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordertime
     *
     * @return the value of order.ordertime
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public String getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordertime
     *
     * @param ordertime the value for order.ordertime
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public void setOrdertime(String ordertime) {
        this.ordertime = ordertime == null ? null : ordertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total
     *
     * @return the value of order.total
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total
     *
     * @param total the value for order.total
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.address
     *
     * @return the value of order.address
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.address
     *
     * @param address the value for order.address
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.uid
     *
     * @return the value of order.uid
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.uid
     *
     * @param uid the value for order.uid
     *
     * @mbggenerated Thu Jun 22 13:54:52 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }
}