package com.cheng.dao;

import com.cheng.cartitem.povo.CartItempovo;
import com.cheng.domain.CartItem;
import com.cheng.domain.CartItemExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CartItemMapper {
	List<CartItempovo> selectCartIempovoByUid(String uid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    int countByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    int deleteByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    int deleteByPrimaryKey(String cartitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    int insert(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    int insertSelective(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    List<CartItem> selectByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    CartItem selectByPrimaryKey(String cartitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") CartItem record, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    int updateByExample(@Param("record") CartItem record, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    int updateByPrimaryKeySelective(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Fri Jun 23 09:56:02 CST 2017
     */
    int updateByPrimaryKey(CartItem record);
}